List<String> gejala = [
  "Daun mudah gugur",
  "Bunga dan buah mengering dan gugur",
  "Terdapat lubang pada ujung buah",
  "Cabang samping jarang tumbuh",
  "Akar membusuk",
  "Tanaman kerdil",
  "Daun menguning",
  "Adanya miselium tipis seperti benang-benang pada bagian bawah tanaman yang terserang.",
  "Cacat pada buah tua",
  "Terdapat bercak berwarna coklat atau kemerahan pada daun",
  "Terdapat bercak berwarna kuning pada daun",
  "Bercak dikelilingi halo (lingkaran) berwarna kuning",
  "Dibalik daun terdapat serbuk berwarna jingga cerah",
  "Terdapat bercak pada buah",
  "Kulit buah terkena bercak menjadi mengeras",
  "Buah berguguran pada kopi muda",
  "Munculnya campuran kotoran dengan serpihan jaringan di dalam cabang atau batang yang rusak",
  "Layu pada ranting atau cabang yang terserang",
  "Buah kopi dan daun tertutupi cendawan dan jelaga",
  "Keadaan busuk sampai ke biji pada buah kopi",
  "Bunga dan buah mengering dan gugur",
  "Adanya serangan jamur jelaga berwarna hitam pada permukaan daun dan cabang kopi.",
  "Buah berguguran pada kopi muda",
  "Pada cabang pohon daun menjadi kering",
  "Terbentuk tepung berwarna jingga pada sisi bawah daun",
  "Pada celah-celah atau lentisel batang kopi terbentuk gambaran hifa dengan warna putih",
  "Keadaan busuk berwarna hitam hingga kecoklatan pada bagian akar",
  "Pada bagian atas dan bawah kamar pupa disumbat oleh sisa-sisa gerekan.",
  "Keadaan akar menjadi lunak, kering dan membusuk",
  "Permukaan kulit batang atau cabang tanaman yang digerek terdapat lubang masuk larva"
];
